/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe. Public, unauthenticated, cheap. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The `error` object inside every error response. */
        ErrorBody: {
            /** @description SCREAMING_SNAKE machine code. */
            code: string;
            /** @description Extra detail, or null when there is none. */
            details?: unknown;
            /** @description Human message. Fixed for 5xx, descriptive for 4xx. */
            message: string;
        };
        /** @description Top-level error envelope. */
        ErrorEnvelope: {
            /** @description The single error payload. */
            error: components["schemas"]["ErrorBody"];
        };
        /** @description Health payload. Shape kept from v2: `status` plus the running message. */
        HealthResponse: {
            /** @description Human-readable running message. */
            message: string;
            /** @description Service state, `ok` when serving. */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
