//! OpenAPI document built with utoipa.
//!
//! The document served at `/openapi.json` is the single contract source:
//! `server/openapi/check.sh` generates TypeScript from it, and CI fails on
//! drift between the committed files and a fresh generation.

use utoipa::OpenApi;

use crate::{
    auth::{
        routes::models::{
            FederatedUserView, JellyfinLoginBody, LoginBody, OidcAuthorizeBody, OidcCallbackQuery,
            OidcExchangeBody, PlexConnectPollResult, PlexLinkPollResult, PlexLoginPollBody,
            PlexLoginPollResult, PlexPinBody, PlexProfileView, PlexStartBody, SetupBody,
            SetupStatusBody, TransportDto,
        },
        users::models::{
            AdminAppPasswordListResponse, AdminAppPasswordView, AdminUserCreate,
            AdminUserListResponse, AppPasswordCreate, AppPasswordCreatedResponse,
            AppPasswordListResponse, AppPasswordView, AvatarUpload, DeviceSessionMint,
            DeviceSessionResponse, DisplayNameUpdate, EmailUpdate, ImportCandidateListResponse,
            ImportCandidateView, ImportUsersRequest, ImportUsersResponse, LastFmConfiguredResponse,
            LastFmCredentialsSet, LastFmSessionExchange, LastFmSessionResponse,
            LastFmStatusResponse, LastFmTokenResponse, LocalPasswordSet, PasswordChange,
            PasswordReset, ProfileResponse, RecoveryCodeResponse, RoleUpdate, SessionListResponse,
            SessionView, UserResponse, UsernameUpdate,
        },
    },
    error::{ErrorBody, ErrorEnvelope},
    handlers::HealthResponse,
    reads::{
        collections::models::{
            AddTracksBody, AddTracksResponse, ApprovalBatchItem, ApprovalBatchListResponse,
            AutoDownloadApprovalItem, AutoDownloadApprovalListResponse, AutoDownloadBody,
            CheckTracksBody, CheckTracksResponse, CoverUploadBody, CoverUploadResponse,
            CreatePlaylistBody, EditionPinBody, EditionPinResponse, FavoriteCounts, FavoriteItem,
            FavoriteListResponse, FavoriteQuery, FavoriteStatusResponse, FollowBody,
            FollowStatusResponse, FollowedArtist, FollowedArtistListResponse, NewReleaseItem,
            NewReleaseListResponse, PlaylistDetail, PlaylistListItem, PlaylistListResponse,
            PlaylistSummary, PlaylistTrack, RedactedPlaylist, RemoveTracksBody,
            RemoveTracksResponse, ReorderBody, ReorderResponse, ResolveSourcesResponse,
            SetFavoriteBody, StatusResponse, TrackIdentifier, TrackInput, UnseenCountResponse,
            UpdatePlaylistBody, UpdateTrackBody, VisibilityBody,
        },
        discover::models::{
            AlbumPreviewResponse, BecauseYouListenTo, ChartAlbum, ChartArtist, ChartGenre,
            ChartRange, ChartSection, ChartSource, ChartTrack, DiscoverActivityRequest,
            DiscoverActivityResponse, DiscoverPreview, DiscoverQueuePreview, DiscoverQueueResponse,
            DiscoverQueueStatusResponse, DiscoverResponse, DiscoveryBatchCreate,
            DiscoveryBatchDetail, DiscoveryBatchItemIn, DiscoveryBatchItemStatus,
            DiscoveryBatchListResponse, DiscoveryBatchRemoveResult, DiscoveryBatchSummary,
            GenreArtwork, GenreArtworkAlbum, GenreDetailResponse, GenreLibrarySection,
            GenrePopularSection, HomeResponse, IgnoredRelease, IgnoredReleasesResponse,
            IntegrationStatus, NowPlayingEntry, NowPlayingSnapshot, PlaylistProfile,
            PlaylistSuggestionsRequest, PlaylistSuggestionsResponse, PopularAlbumsPage,
            PreviewTrackItem, QueueEnrichment, QueueGenerateRequest, QueueGenerateResponse,
            QueueIgnoreRequest, QueueItem, QueueItemFull, QueueItemLight, QueueValidateRequest,
            QueueValidateResponse, RadioPlanRequest, RadioPlanResponse, RadioPlanTrack,
            RadioRequest, RadioSeedItem, RefreshResponse, SectionItem, ServicePrompt, TopPickItem,
            TopPicksSection, TrackCacheCheckItem, TrackCacheCheckRequest, TrackCacheCheckResponse,
            TrackCacheCheckResponseItem, TrackPreviewResponse, TrendingArtistsPage,
            WeeklyExploration, WeeklyTrack, YouTubeQuotaResponse, YouTubeSearchResponse,
        },
        library::models::{
            AlbumCard, AlbumCardPage, AlbumPage, AlbumView, ArtistPage, ArtistView, DecadeShelf,
            DecadesResponse, GenreList, GenreView, LyricLine, LyricsView, SearchResults, StatsView,
            SuggestionTrack, SuggestionsResponse, TrackPage, TrackView,
        },
        platform::{
            version::{GitHubRelease, UpdateCheckResponse, VersionInfo},
            wrapped::{
                ServerWrappedResponse, UserWrappedResponse, WrappedAlbum, WrappedArtist,
                WrappedGenre, WrappedLeaderboardEntry, WrappedTrack, WrappedUserSummary,
                WrappedUsersResponse,
            },
        },
        search::models::{
            AlbumEnrichment, AlbumEnrichmentRequest, ArtistEnrichment, ArtistEnrichmentRequest,
            Degradation, EnrichmentBatchRequest, EnrichmentResponse, EnrichmentSource,
            SearchBucketResponse, SearchKind, SearchResponse, SearchResultItem, SuggestResponse,
            SuggestResult,
        },
    },
};

/// Native API contract document.
#[derive(OpenApi)]
#[openapi(
    paths(
        crate::handlers::health,
        crate::auth::users::handlers::get_profile,
        crate::auth::users::handlers::patch_profile,
        crate::auth::users::handlers::put_username,
        crate::auth::users::handlers::put_email,
        crate::auth::users::handlers::post_password,
        crate::auth::users::handlers::post_local_password,
        crate::auth::users::handlers::post_avatar,
        crate::auth::users::handlers::get_avatar,
        crate::auth::users::handlers::list_sessions,
        crate::auth::users::handlers::mint_device_session,
        crate::auth::users::handlers::revoke_session,
        crate::auth::users::handlers::logout_all,
        crate::auth::users::handlers::reset_password,
        crate::auth::users::handlers::list_app_passwords,
        crate::auth::users::handlers::create_app_password,
        crate::auth::users::handlers::revoke_app_password,
        crate::auth::users::handlers::lastfm_status,
        crate::auth::users::handlers::lastfm_set_credentials,
        crate::auth::users::handlers::lastfm_token,
        crate::auth::users::handlers::lastfm_session,
        crate::auth::users::handlers::lastfm_unlink,
        crate::auth::users::handlers::admin_list_users,
        crate::auth::users::handlers::admin_create_user,
        crate::auth::users::handlers::admin_get_user,
        crate::auth::users::handlers::admin_set_role,
        crate::auth::users::handlers::admin_delete_user,
        crate::auth::users::handlers::admin_revoke_sessions,
        crate::auth::users::handlers::admin_mint_recovery_code,
        crate::auth::users::handlers::admin_list_app_passwords,
        crate::auth::users::handlers::admin_revoke_app_password,
        crate::auth::users::handlers::admin_import_list_jellyfin,
        crate::auth::users::handlers::admin_import_list_plex,
        crate::auth::users::handlers::admin_import_users,
        crate::auth::routes::native::login_handler,
        crate::auth::routes::native::logout_handler,
        crate::auth::routes::native::setup_handler,
        crate::auth::routes::native::setup_status_handler,
        crate::auth::routes::federated::oidc_authorize_handler,
        crate::auth::routes::federated::oidc_callback_handler,
        crate::auth::routes::federated::oidc_exchange_handler,
        crate::auth::routes::federated::jellyfin_login_handler,
        crate::auth::routes::federated::plex_start_handler,
        crate::auth::routes::federated::plex_poll_login_handler,
        crate::auth::routes::federated::plex_poll_link_handler,
        crate::auth::routes::federated::plex_poll_connect_handler,
        crate::reads::library::handlers::list_albums,
        crate::reads::library::handlers::get_album,
        crate::reads::library::handlers::list_album_tracks,
        crate::reads::library::handlers::list_album_copies,
        crate::reads::library::handlers::list_artists,
        crate::reads::library::handlers::get_artist,
        crate::reads::library::handlers::list_artist_albums,
        crate::reads::library::handlers::list_artist_appearances,
        crate::reads::library::handlers::list_tracks,
        crate::reads::library::handlers::get_track,
        crate::reads::library::handlers::get_lyrics,
        crate::reads::library::handlers::get_stats,
        crate::reads::library::handlers::list_recently_added,
        crate::reads::library::handlers::list_genres,
        crate::reads::library::handlers::list_genre_tracks,
        crate::reads::library::handlers::browse_albums,
        crate::reads::library::handlers::search_library,
        crate::reads::library::handlers::recent_albums,
        crate::reads::library::handlers::list_decades,
        crate::reads::library::handlers::list_suggestions,
        crate::reads::search::handlers::search,
        crate::reads::search::handlers::search_bucket,
        crate::reads::search::handlers::suggest,
        crate::reads::search::handlers::enrich_batch,
        crate::reads::discover::handlers::get_discover,
        crate::reads::discover::handlers::refresh_discover,
        crate::reads::discover::handlers::record_activity,
        crate::reads::discover::handlers::discover_radio,
        crate::reads::discover::handlers::radio_plan,
        crate::reads::discover::handlers::playlist_suggestions,
        crate::reads::discover::handlers::get_queue,
        crate::reads::discover::handlers::queue_status,
        crate::reads::discover::handlers::queue_generate,
        crate::reads::discover::handlers::enrich_queue_item,
        crate::reads::discover::handlers::preview_queue_item,
        crate::reads::discover::handlers::ignore_queue_item,
        crate::reads::discover::handlers::ignored_releases,
        crate::reads::discover::handlers::validate_queue,
        crate::reads::discover::handlers::youtube_search,
        crate::reads::discover::handlers::youtube_track_search,
        crate::reads::discover::handlers::youtube_quota,
        crate::reads::discover::handlers::youtube_cache_check,
        crate::reads::discover::handlers::track_preview,
        crate::reads::discover::handlers::album_preview,
        crate::reads::discover::handlers::create_batch,
        crate::reads::discover::handlers::list_batches,
        crate::reads::discover::handlers::get_batch,
        crate::reads::discover::handlers::remove_batch,
        crate::reads::discover::handlers::get_home,
        crate::reads::discover::handlers::integration_status,
        crate::reads::discover::handlers::genre_detail,
        crate::reads::discover::handlers::trending_artists,
        crate::reads::discover::handlers::popular_albums,
        crate::reads::discover::handlers::your_top_albums,
        crate::reads::discover::handlers::now_playing,
        crate::reads::collections::playlists::list_playlists_handler,
        crate::reads::collections::playlists::create_playlist_handler,
        crate::reads::collections::playlists::get_playlist_handler,
        crate::reads::collections::playlists::update_playlist_handler,
        crate::reads::collections::playlists::delete_playlist_handler,
        crate::reads::collections::playlists::set_visibility_handler,
        crate::reads::collections::playlists::add_tracks_handler,
        crate::reads::collections::playlists::remove_tracks_handler,
        crate::reads::collections::playlists::remove_track_handler,
        crate::reads::collections::playlists::reorder_track_handler,
        crate::reads::collections::playlists::update_track_handler,
        crate::reads::collections::playlists::check_tracks_handler,
        crate::reads::collections::playlists::resolve_sources_handler,
        crate::reads::collections::playlists::upload_cover_handler,
        crate::reads::collections::playlists::get_cover_handler,
        crate::reads::collections::playlists::remove_cover_handler,
        crate::reads::collections::favorites::list_favorites_handler,
        crate::reads::collections::favorites::set_favorite_handler,
        crate::reads::collections::follows::get_follow_status_handler,
        crate::reads::collections::follows::set_follow_handler,
        crate::reads::collections::follows::set_auto_download_handler,
        crate::reads::collections::follows::list_followed_artists_handler,
        crate::reads::collections::follows::list_new_releases_handler,
        crate::reads::collections::follows::list_recent_releases_handler,
        crate::reads::collections::follows::unseen_count_handler,
        crate::reads::collections::follows::mark_seen_handler,
        crate::reads::collections::approvals::list_approvals_handler,
        crate::reads::collections::approvals::list_approval_batches_handler,
        crate::reads::collections::pins::get_pin_handler,
        crate::reads::collections::pins::set_pin_handler,
        crate::reads::collections::pins::clear_pin_handler,
        crate::reads::platform::covers::cover_from_release_group,
        crate::reads::platform::covers::cover_from_release,
        crate::reads::platform::covers::artist_cover,
        crate::reads::platform::version::get_version,
        crate::reads::platform::version::check_update,
        crate::reads::platform::version::get_releases,
        crate::reads::platform::wrapped::get_wrapped_users,
        crate::reads::platform::wrapped::get_wrapped_user,
        crate::reads::platform::wrapped::get_wrapped_server,
    ),
    components(schemas(
        HealthResponse,
        ErrorEnvelope,
        ErrorBody,
        UserResponse,
        ProfileResponse,
        DisplayNameUpdate,
        UsernameUpdate,
        EmailUpdate,
        PasswordChange,
        LocalPasswordSet,
        AvatarUpload,
        SessionView,
        SessionListResponse,
        DeviceSessionMint,
        DeviceSessionResponse,
        AdminUserCreate,
        AdminUserListResponse,
        RoleUpdate,
        RecoveryCodeResponse,
        PasswordReset,
        LastFmStatusResponse,
        LastFmCredentialsSet,
        LastFmConfiguredResponse,
        LastFmTokenResponse,
        LastFmSessionExchange,
        LastFmSessionResponse,
        AppPasswordView,
        AppPasswordListResponse,
        AppPasswordCreate,
        AppPasswordCreatedResponse,
        AdminAppPasswordView,
        AdminAppPasswordListResponse,
        ImportCandidateView,
        ImportCandidateListResponse,
        ImportUsersRequest,
        ImportUsersResponse,
        TransportDto,
        LoginBody,
        SetupBody,
        SetupStatusBody,
        FederatedUserView,
        JellyfinLoginBody,
        OidcCallbackQuery,
        OidcAuthorizeBody,
        OidcExchangeBody,
        PlexStartBody,
        PlexPinBody,
        PlexLoginPollBody,
        PlexLoginPollResult,
        PlexProfileView,
        PlexLinkPollResult,
        PlexConnectPollResult,
        AlbumCard,
        AlbumCardPage,
        AlbumPage,
        AlbumView,
        ArtistPage,
        ArtistView,
        DecadeShelf,
        DecadesResponse,
        GenreList,
        GenreView,
        LyricLine,
        LyricsView,
        SearchResults,
        StatsView,
        SuggestionTrack,
        SuggestionsResponse,
        TrackPage,
        TrackView,
        AlbumEnrichment,
        AlbumEnrichmentRequest,
        ArtistEnrichment,
        ArtistEnrichmentRequest,
        Degradation,
        EnrichmentBatchRequest,
        EnrichmentResponse,
        EnrichmentSource,
        SearchBucketResponse,
        SearchKind,
        SearchResponse,
        SearchResultItem,
        SuggestResponse,
        SuggestResult,
        AlbumPreviewResponse,
        BecauseYouListenTo,
        ChartAlbum,
        ChartArtist,
        ChartGenre,
        ChartRange,
        ChartSection,
        ChartSource,
        ChartTrack,
        DiscoverActivityRequest,
        DiscoverActivityResponse,
        DiscoverPreview,
        DiscoverQueuePreview,
        DiscoverQueueResponse,
        DiscoverQueueStatusResponse,
        DiscoverResponse,
        DiscoveryBatchCreate,
        DiscoveryBatchDetail,
        DiscoveryBatchItemIn,
        DiscoveryBatchItemStatus,
        DiscoveryBatchListResponse,
        DiscoveryBatchRemoveResult,
        DiscoveryBatchSummary,
        GenreArtwork,
        GenreArtworkAlbum,
        GenreDetailResponse,
        GenreLibrarySection,
        GenrePopularSection,
        HomeResponse,
        IgnoredRelease,
        IgnoredReleasesResponse,
        IntegrationStatus,
        NowPlayingEntry,
        NowPlayingSnapshot,
        PlaylistProfile,
        PlaylistSuggestionsRequest,
        PlaylistSuggestionsResponse,
        PopularAlbumsPage,
        PreviewTrackItem,
        QueueEnrichment,
        QueueGenerateRequest,
        QueueGenerateResponse,
        QueueIgnoreRequest,
        QueueItem,
        QueueItemFull,
        QueueItemLight,
        QueueValidateRequest,
        QueueValidateResponse,
        RadioPlanRequest,
        RadioPlanResponse,
        RadioPlanTrack,
        RadioRequest,
        RadioSeedItem,
        RefreshResponse,
        SectionItem,
        ServicePrompt,
        TopPickItem,
        TopPicksSection,
        TrackCacheCheckItem,
        TrackCacheCheckRequest,
        TrackCacheCheckResponse,
        TrackCacheCheckResponseItem,
        TrackPreviewResponse,
        TrendingArtistsPage,
        WeeklyExploration,
        WeeklyTrack,
        YouTubeQuotaResponse,
        YouTubeSearchResponse,
        AddTracksBody,
        AddTracksResponse,
        ApprovalBatchItem,
        ApprovalBatchListResponse,
        AutoDownloadApprovalItem,
        AutoDownloadApprovalListResponse,
        AutoDownloadBody,
        CheckTracksBody,
        CheckTracksResponse,
        CoverUploadBody,
        CoverUploadResponse,
        CreatePlaylistBody,
        EditionPinBody,
        EditionPinResponse,
        FavoriteCounts,
        FavoriteItem,
        FavoriteListResponse,
        FavoriteQuery,
        FavoriteStatusResponse,
        FollowBody,
        FollowStatusResponse,
        FollowedArtist,
        FollowedArtistListResponse,
        NewReleaseItem,
        NewReleaseListResponse,
        PlaylistDetail,
        PlaylistListItem,
        PlaylistListResponse,
        PlaylistSummary,
        PlaylistTrack,
        RedactedPlaylist,
        RemoveTracksBody,
        RemoveTracksResponse,
        ReorderBody,
        ReorderResponse,
        ResolveSourcesResponse,
        SetFavoriteBody,
        StatusResponse,
        TrackIdentifier,
        TrackInput,
        UnseenCountResponse,
        UpdatePlaylistBody,
        UpdateTrackBody,
        VisibilityBody,
        GitHubRelease,
        UpdateCheckResponse,
        VersionInfo,
        ServerWrappedResponse,
        UserWrappedResponse,
        WrappedAlbum,
        WrappedArtist,
        WrappedGenre,
        WrappedLeaderboardEntry,
        WrappedTrack,
        WrappedUserSummary,
        WrappedUsersResponse,
    )),
    info(
        title = "DroppedNeedle v3",
        version = "3.0.0",
        description = "Native API contract. Generated clients must never be hand-edited."
    )
)]
pub struct ApiDoc;
