//! OpenAPI document built with utoipa.
//!
//! The document served at `/openapi.json` is the single contract source:
//! `server/openapi/check.sh` generates TypeScript from it, and CI fails on
//! drift between the committed files and a fresh generation.

use utoipa::OpenApi;

use crate::{
    auth::{
        routes::models::{
            FederatedUserView, JellyfinLoginBody, LoginBody, OidcAuthorizeBody, OidcCallbackQuery,
            OidcExchangeBody, PlexConnectPollResult, PlexLinkPollResult, PlexLoginPollBody,
            PlexLoginPollResult, PlexPinBody, PlexProfileView, PlexStartBody, SetupBody,
            SetupStatusBody, TransportDto,
        },
        users::models::{
            AdminAppPasswordListResponse, AdminAppPasswordView, AdminUserCreate,
            AdminUserListResponse, AppPasswordCreate, AppPasswordCreatedResponse,
            AppPasswordListResponse, AppPasswordView, AvatarUpload, DeviceSessionMint,
            DeviceSessionResponse, DisplayNameUpdate, EmailUpdate, ImportCandidateListResponse,
            ImportCandidateView, ImportUsersRequest, ImportUsersResponse, LastFmConfiguredResponse,
            LastFmCredentialsSet, LastFmSessionExchange, LastFmSessionResponse,
            LastFmStatusResponse, LastFmTokenResponse, LocalPasswordSet, PasswordChange,
            PasswordReset, ProfileResponse, RecoveryCodeResponse, RoleUpdate, SessionListResponse,
            SessionView, UserResponse, UsernameUpdate,
        },
    },
    error::{ErrorBody, ErrorEnvelope},
    handlers::HealthResponse,
};

/// Native API contract document.
#[derive(OpenApi)]
#[openapi(
    paths(
        crate::handlers::health,
        crate::auth::users::handlers::get_profile,
        crate::auth::users::handlers::patch_profile,
        crate::auth::users::handlers::put_username,
        crate::auth::users::handlers::put_email,
        crate::auth::users::handlers::post_password,
        crate::auth::users::handlers::post_local_password,
        crate::auth::users::handlers::post_avatar,
        crate::auth::users::handlers::get_avatar,
        crate::auth::users::handlers::list_sessions,
        crate::auth::users::handlers::mint_device_session,
        crate::auth::users::handlers::revoke_session,
        crate::auth::users::handlers::logout_all,
        crate::auth::users::handlers::reset_password,
        crate::auth::users::handlers::list_app_passwords,
        crate::auth::users::handlers::create_app_password,
        crate::auth::users::handlers::revoke_app_password,
        crate::auth::users::handlers::lastfm_status,
        crate::auth::users::handlers::lastfm_set_credentials,
        crate::auth::users::handlers::lastfm_token,
        crate::auth::users::handlers::lastfm_session,
        crate::auth::users::handlers::lastfm_unlink,
        crate::auth::users::handlers::admin_list_users,
        crate::auth::users::handlers::admin_create_user,
        crate::auth::users::handlers::admin_get_user,
        crate::auth::users::handlers::admin_set_role,
        crate::auth::users::handlers::admin_delete_user,
        crate::auth::users::handlers::admin_revoke_sessions,
        crate::auth::users::handlers::admin_mint_recovery_code,
        crate::auth::users::handlers::admin_list_app_passwords,
        crate::auth::users::handlers::admin_revoke_app_password,
        crate::auth::users::handlers::admin_import_list_jellyfin,
        crate::auth::users::handlers::admin_import_list_plex,
        crate::auth::users::handlers::admin_import_users,
        crate::auth::routes::native::login_handler,
        crate::auth::routes::native::logout_handler,
        crate::auth::routes::native::setup_handler,
        crate::auth::routes::native::setup_status_handler,
        crate::auth::routes::federated::oidc_authorize_handler,
        crate::auth::routes::federated::oidc_callback_handler,
        crate::auth::routes::federated::oidc_exchange_handler,
        crate::auth::routes::federated::jellyfin_login_handler,
        crate::auth::routes::federated::plex_start_handler,
        crate::auth::routes::federated::plex_poll_login_handler,
        crate::auth::routes::federated::plex_poll_link_handler,
        crate::auth::routes::federated::plex_poll_connect_handler,
    ),
    components(schemas(
        HealthResponse,
        ErrorEnvelope,
        ErrorBody,
        UserResponse,
        ProfileResponse,
        DisplayNameUpdate,
        UsernameUpdate,
        EmailUpdate,
        PasswordChange,
        LocalPasswordSet,
        AvatarUpload,
        SessionView,
        SessionListResponse,
        DeviceSessionMint,
        DeviceSessionResponse,
        AdminUserCreate,
        AdminUserListResponse,
        RoleUpdate,
        RecoveryCodeResponse,
        PasswordReset,
        LastFmStatusResponse,
        LastFmCredentialsSet,
        LastFmConfiguredResponse,
        LastFmTokenResponse,
        LastFmSessionExchange,
        LastFmSessionResponse,
        AppPasswordView,
        AppPasswordListResponse,
        AppPasswordCreate,
        AppPasswordCreatedResponse,
        AdminAppPasswordView,
        AdminAppPasswordListResponse,
        ImportCandidateView,
        ImportCandidateListResponse,
        ImportUsersRequest,
        ImportUsersResponse,
        TransportDto,
        LoginBody,
        SetupBody,
        SetupStatusBody,
        FederatedUserView,
        JellyfinLoginBody,
        OidcCallbackQuery,
        OidcAuthorizeBody,
        OidcExchangeBody,
        PlexStartBody,
        PlexPinBody,
        PlexLoginPollBody,
        PlexLoginPollResult,
        PlexProfileView,
        PlexLinkPollResult,
        PlexConnectPollResult,
    )),
    info(
        title = "DroppedNeedle v3",
        version = "3.0.0",
        description = "Native API contract. Generated clients must never be hand-edited."
    )
)]
pub struct ApiDoc;
