//! OpenAPI document built with utoipa.
//!
//! The document served at `/openapi.json` is the single contract source:
//! `server/openapi/check.sh` generates TypeScript from it, and CI fails on
//! drift between the committed files and a fresh generation.

use utoipa::OpenApi;

use crate::{
    acquire::{
        downloads::http::ReimportResponse,
        imports::models::{
            AcquireHealth, LidarrArtistCandidate, LidarrArtistListResponse,
            LidarrConnectionSettings, LidarrImportRequest, LidarrImportResponse,
            LidarrTestResponse, SabnzbdStatusResponse, SlskdStatusResponse, SourceGate,
            SpotifyAuthUrlResponse, SpotifyImportRequest, SpotifyImportResponse, SpotifyJobStatus,
            SpotifyPlaylistItem, SpotifyPlaylistListResponse, SpotifyRedirectUri, SpotifySettings,
        },
        requests::models::{
            ActionResponse, ActiveCountResponse, ActiveRequestsResponse, AlbumIntake,
            BatchCancelBody, BatchCancelResponse, BatchIntake, BatchIntakeResponse, BatchItem,
            ClearHistoryResponse, EditionAcquireResponse, HistoryQuery, HistoryResponse,
            IntakeResponse, KindQuery, PersonalMixApprovalItem, PersonalMixApprovalsResponse,
            RefreshResponse as RequestsRefreshResponse, RequestItem, RequestStatusMessage,
            SyncResponse, TrackIntake, TrackIntakeResponse, WantedActionResponse, WantedItem,
            WantedResponse, WantedRetryingItem,
        },
    },
    admin::{
        BackupListResponse, BackupRunResponse, BackupView, CacheClearBody, CacheClearResponse,
        CacheStatsResponse, CheckpointView, JobView, PrecacheRunResponse, ProviderLimiterView,
        ProviderStatsResponse, QueueStatsResponse, QuotaOverrideBody, QuotaOverrideView,
        QuotaResponse, RestoreCheck, RestoreReport, SlotView, WakeupChannelView,
    },
    auth::{
        routes::models::{
            FederatedUserView, JellyfinLoginBody, LoginBody, OidcAuthorizeBody, OidcCallbackQuery,
            OidcExchangeBody, PlexConnectPollResult, PlexLinkPollResult, PlexLoginPollBody,
            PlexLoginPollResult, PlexPinBody, PlexProfileView, PlexStartBody, SetupBody,
            SetupStatusBody, TransportDto,
        },
        users::models::{
            AdminAppPasswordListResponse, AdminAppPasswordView, AdminUserCreate,
            AdminUserListResponse, AppPasswordCreate, AppPasswordCreatedResponse,
            AppPasswordListResponse, AppPasswordView, AvatarUpload, DeviceSessionMint,
            DeviceSessionResponse, DisplayNameUpdate, EmailUpdate, ImportCandidateListResponse,
            ImportCandidateView, ImportUsersRequest, ImportUsersResponse, LastFmConfiguredResponse,
            LastFmCredentialsSet, LastFmSessionExchange, LastFmSessionResponse,
            LastFmStatusResponse, LastFmTokenResponse, LocalPasswordSet, PasswordChange,
            PasswordReset, ProfileResponse, RecoveryCodeResponse, RoleUpdate, SessionListResponse,
            SessionView, UserResponse, UsernameUpdate,
        },
    },
    error::{ErrorBody, ErrorEnvelope},
    handlers::HealthResponse,
    library::http::models::{
        AddRootBody, ApproveBody, BaselineRestoreBody, BaselineRestoreResponse, CandidateView,
        IdentifyBody, IdentifyResponse, IdentityView, ManageAppliedFile, ManageApplyBody,
        ManageApplyResponse, ManageFileView, ManageItemBody, ManagePreviewBody,
        ManagePreviewResponse, ManageUndoBody, ManageUndoResponse, ReviewResolveResponse,
        ReviewView, ReviewsResponse, RootView, RootsResponse, RunDetailResponse, ScanBody,
        ScanFileView, ScanResponse, ScanRunView, ScanRunsResponse, ScanScopeView,
    },
    playback::models::{
        NowPlayingDeleteQuery, NowPlayingEntry, NowPlayingHeartbeat, NowPlayingSnapshot,
        PlaybackProgressRequest, PlaybackProgressResponse, PlaybackStartRequest,
        PlaybackStartResponse, PlaybackStopRequest, PlaybackStopResponse,
        ScrobbleNowPlayingRequest, ScrobbleResponse, ScrobbleSubmitRequest, ServiceResult,
    },
    plugins::models::{
        ConnectionStatus as PluginConnectionStatus, ListenBrainzConnectRequest, PluginInfo,
        PluginInstallRequest, PluginListResponse, PluginSettingFieldInfo, PluginSource,
        PluginSourcesResponse, PluginUpdateRequest, ScrobblePreferences, ScrobblePreferencesUpdate,
        StatusMessage,
    },
    reads::{
        collections::models::{
            AddTracksBody, AddTracksResponse, ApprovalBatchItem, ApprovalBatchListResponse,
            AutoDownloadApprovalItem, AutoDownloadApprovalListResponse, AutoDownloadBody,
            CheckTracksBody, CheckTracksResponse, CoverUploadBody, CoverUploadResponse,
            CreatePlaylistBody, EditionPinBody, EditionPinResponse, FavoriteCounts, FavoriteItem,
            FavoriteListResponse, FavoriteQuery, FavoriteStatusResponse, FollowBody,
            FollowStatusResponse, FollowedArtist, FollowedArtistListResponse, NewReleaseItem,
            NewReleaseListResponse, PlaylistDetail, PlaylistListItem, PlaylistListResponse,
            PlaylistSummary, PlaylistTrack, RedactedPlaylist, RemoveTracksBody,
            RemoveTracksResponse, ReorderBody, ReorderResponse, ResolveSourcesResponse,
            SetFavoriteBody, StatusResponse, TrackIdentifier, TrackInput, UnseenCountResponse,
            UpdatePlaylistBody, UpdateTrackBody, VisibilityBody,
        },
        discover::models::{
            AlbumPreviewResponse, BecauseYouListenTo, ChartAlbum, ChartArtist, ChartGenre,
            ChartRange, ChartSection, ChartSource, ChartTrack, DiscoverActivityRequest,
            DiscoverActivityResponse, DiscoverPreview, DiscoverQueuePreview, DiscoverQueueResponse,
            DiscoverQueueStatusResponse, DiscoverResponse, DiscoveryBatchCreate,
            DiscoveryBatchDetail, DiscoveryBatchItemIn, DiscoveryBatchItemStatus,
            DiscoveryBatchListResponse, DiscoveryBatchRemoveResult, DiscoveryBatchSummary,
            GenreArtwork, GenreArtworkAlbum, GenreDetailResponse, GenreLibrarySection,
            GenrePopularSection, HomeResponse, IgnoredRelease, IgnoredReleasesResponse,
            IntegrationStatus, PlaylistProfile, PlaylistSuggestionsRequest,
            PlaylistSuggestionsResponse, PopularAlbumsPage, PreviewTrackItem, QueueEnrichment,
            QueueGenerateRequest, QueueGenerateResponse, QueueIgnoreRequest, QueueItem,
            QueueItemFull, QueueItemLight, QueueValidateRequest, QueueValidateResponse,
            RadioPlanRequest, RadioPlanResponse, RadioPlanTrack, RadioRequest, RadioSeedItem,
            RefreshResponse, SectionItem, ServicePrompt, TopPickItem, TopPicksSection,
            TrackCacheCheckItem, TrackCacheCheckRequest, TrackCacheCheckResponse,
            TrackCacheCheckResponseItem, TrackPreviewResponse, TrendingArtistsPage,
            WeeklyExploration, WeeklyTrack, YouTubeQuotaResponse, YouTubeSearchResponse,
        },
        library::models::{
            AlbumCard, AlbumCardPage, AlbumPage, AlbumView, ArtistPage, ArtistView, DecadeShelf,
            DecadesResponse, GenreList, GenreView, LyricLine, LyricsView, SearchResults, StatsView,
            SuggestionTrack, SuggestionsResponse, TrackPage, TrackView,
        },
        platform::{
            version::{GitHubRelease, UpdateCheckResponse, VersionInfo},
            wrapped::{
                ServerWrappedResponse, UserWrappedResponse, WrappedAlbum, WrappedArtist,
                WrappedGenre, WrappedLeaderboardEntry, WrappedTrack, WrappedUserSummary,
                WrappedUsersResponse,
            },
        },
        search::models::{
            AlbumEnrichment, AlbumEnrichmentRequest, ArtistEnrichment, ArtistEnrichmentRequest,
            Degradation, EnrichmentBatchRequest, EnrichmentResponse, EnrichmentSource,
            SearchBucketResponse, SearchKind, SearchResponse, SearchResultItem, SuggestResponse,
            SuggestResult,
        },
    },
    remotes::models::{
        AlbumPage as RemotesAlbumPage, AlbumView as RemotesAlbumView, ArtistIndex,
        ArtistIndexEntry, ArtistPage as RemotesArtistPage, ArtistView as RemotesArtistView,
        ConnectionSave, ConnectionStatus, DiscoveryHubView, DiscoveryView, FavoritesView,
        FolderResolutionView, FolderSave, HistoryEntry, HistoryPage, HubView, ImportResult,
        InfoView, LyricLine as RemotesLyricLine, LyricsView as RemotesLyricsView, MatchView,
        MusicFolderView, PlaylistCollection, PlaylistDetail as RemotesPlaylistDetail,
        PlaylistSummary as RemotesPlaylistSummary, SearchResults as RemotesSearchResults,
        SessionView as RemotesSessionView, SessionsView, SourceName, StatsView as RemotesStatsView,
        TrackPage as RemotesTrackPage, TrackView as RemotesTrackView,
    },
    settings::models::{
        AdvancedSettingsDto, AudioFormatDto, BrainzmashActiveBindingDto,
        BrainzmashPendingProposalDto, ConnectAppsDto, DiscoverModeDto, DownloadAccessDto,
        DownloadPolicyDto, EventsSettingsDto, EventsSweepScopeDto, FilesystemWatcherDto,
        FreeMusicDto, FrontendCacheTTLs, GetItDto, IdentificationPolicyDto, IndexerReorderRequest,
        IndexerSavedResponse, IndexerTestResponse, JellyfinConnectionDto, JellyfinUserInfo,
        JellyfinVerifyResponse, LastFmSettingsDto, LibraryPathRequest, LibraryPathRuleDto,
        LibraryRootDto, LibraryScanScheduleDto, LibraryScanScheduleResponse, LibrarySettingsDto,
        LibrarySettingsResponse, LibrarySettingsSaveRequest, ListenBrainzConnectionDto,
        MbSourceModeDto, MusicBrainzBindingRequest, MusicBrainzSettingsDto,
        MusicBrainzSettingsUpdate, MusicBrainzVerifyRequest, MusicSourceDto,
        NavidromeConnectionDto, NewznabIndexerDto, OidcConnectionDto, OperationResult,
        PlexConnectionDto, PlexLibrarySectionInfo, PlexVerifyResponse, PolicyImpactResponse,
        PolicySummaryResponse, PrimaryMusicSourceDto, ProwlarrConnectionDto, ProwlarrTestResponse,
        QualityRecipeEntryDto, SabnzbdConnectionDto, SabnzbdTestResponse, ScanFrequencyDto,
        ScrobbleSettingsDto, SectionPrefItem, SectionPrefUpdateItem, SectionPrefsResponse,
        SectionPrefsUpdate, SecuritySettingsDto, SlskdConnectionDto, SourcePriorityDto,
        TestConnectionResponse, UsenetBackendDto, UsenetSearchBackendDto, UserPreferencesDto,
        VerifyConnectionResponse, WantedWatcherDto, WrappedSettingsDto, YouTubeConnectionDto,
    },
};

/// Native API contract document.
#[derive(OpenApi)]
#[openapi(
    paths(
        crate::handlers::health,
        crate::auth::users::handlers::get_profile,
        crate::auth::users::handlers::patch_profile,
        crate::auth::users::handlers::put_username,
        crate::auth::users::handlers::put_email,
        crate::auth::users::handlers::post_password,
        crate::auth::users::handlers::post_local_password,
        crate::auth::users::handlers::post_avatar,
        crate::auth::users::handlers::get_avatar,
        crate::auth::users::handlers::list_sessions,
        crate::auth::users::handlers::mint_device_session,
        crate::auth::users::handlers::revoke_session,
        crate::auth::users::handlers::logout_all,
        crate::auth::users::handlers::reset_password,
        crate::auth::users::handlers::list_app_passwords,
        crate::auth::users::handlers::create_app_password,
        crate::auth::users::handlers::revoke_app_password,
        crate::auth::users::handlers::lastfm_status,
        crate::auth::users::handlers::lastfm_set_credentials,
        crate::auth::users::handlers::lastfm_token,
        crate::auth::users::handlers::lastfm_session,
        crate::auth::users::handlers::lastfm_unlink,
        crate::auth::users::handlers::admin_list_users,
        crate::auth::users::handlers::admin_create_user,
        crate::auth::users::handlers::admin_get_user,
        crate::auth::users::handlers::admin_set_role,
        crate::auth::users::handlers::admin_delete_user,
        crate::auth::users::handlers::admin_revoke_sessions,
        crate::auth::users::handlers::admin_mint_recovery_code,
        crate::auth::users::handlers::admin_list_app_passwords,
        crate::auth::users::handlers::admin_revoke_app_password,
        crate::auth::users::handlers::admin_import_list_jellyfin,
        crate::auth::users::handlers::admin_import_list_plex,
        crate::auth::users::handlers::admin_import_users,
        crate::auth::routes::native::login_handler,
        crate::auth::routes::native::logout_handler,
        crate::auth::routes::native::setup_handler,
        crate::auth::routes::native::setup_status_handler,
        crate::auth::routes::federated::oidc_authorize_handler,
        crate::auth::routes::federated::oidc_callback_handler,
        crate::auth::routes::federated::oidc_exchange_handler,
        crate::auth::routes::federated::jellyfin_login_handler,
        crate::auth::routes::federated::plex_start_handler,
        crate::auth::routes::federated::plex_poll_login_handler,
        crate::auth::routes::federated::plex_poll_link_handler,
        crate::auth::routes::federated::plex_poll_connect_handler,
        crate::reads::library::handlers::list_albums,
        crate::reads::library::handlers::get_album,
        crate::reads::library::handlers::list_album_tracks,
        crate::reads::library::handlers::list_album_copies,
        crate::reads::library::handlers::list_artists,
        crate::reads::library::handlers::get_artist,
        crate::reads::library::handlers::list_artist_albums,
        crate::reads::library::handlers::list_artist_appearances,
        crate::reads::library::handlers::list_tracks,
        crate::reads::library::handlers::get_track,
        crate::reads::library::handlers::get_lyrics,
        crate::reads::library::handlers::get_stats,
        crate::reads::library::handlers::list_recently_added,
        crate::reads::library::handlers::list_genres,
        crate::reads::library::handlers::list_genre_tracks,
        crate::reads::library::handlers::browse_albums,
        crate::reads::library::handlers::search_library,
        crate::reads::library::handlers::recent_albums,
        crate::reads::library::handlers::list_decades,
        crate::reads::library::handlers::list_suggestions,
        crate::reads::library::handlers::match_album,
        crate::reads::search::handlers::search,
        crate::reads::search::handlers::search_bucket,
        crate::reads::search::handlers::suggest,
        crate::reads::search::handlers::enrich_batch,
        crate::reads::discover::handlers::get_discover,
        crate::reads::discover::handlers::refresh_discover,
        crate::reads::discover::handlers::record_activity,
        crate::reads::discover::handlers::discover_radio,
        crate::reads::discover::handlers::radio_plan,
        crate::reads::discover::handlers::playlist_suggestions,
        crate::reads::discover::handlers::get_queue,
        crate::reads::discover::handlers::queue_status,
        crate::reads::discover::handlers::queue_generate,
        crate::reads::discover::handlers::enrich_queue_item,
        crate::reads::discover::handlers::preview_queue_item,
        crate::reads::discover::handlers::ignore_queue_item,
        crate::reads::discover::handlers::ignored_releases,
        crate::reads::discover::handlers::validate_queue,
        crate::reads::discover::handlers::youtube_search,
        crate::reads::discover::handlers::youtube_track_search,
        crate::reads::discover::handlers::youtube_quota,
        crate::reads::discover::handlers::youtube_cache_check,
        crate::reads::discover::handlers::track_preview,
        crate::reads::discover::handlers::album_preview,
        crate::reads::discover::handlers::create_batch,
        crate::reads::discover::handlers::list_batches,
        crate::reads::discover::handlers::get_batch,
        crate::reads::discover::handlers::remove_batch,
        crate::reads::discover::handlers::get_home,
        crate::reads::discover::handlers::integration_status,
        crate::reads::discover::handlers::genre_detail,
        crate::reads::discover::handlers::trending_artists,
        crate::reads::discover::handlers::popular_albums,
        crate::reads::discover::handlers::your_top_albums,
        crate::reads::collections::playlists::list_playlists_handler,
        crate::reads::collections::playlists::create_playlist_handler,
        crate::reads::collections::playlists::get_playlist_handler,
        crate::reads::collections::playlists::update_playlist_handler,
        crate::reads::collections::playlists::delete_playlist_handler,
        crate::reads::collections::playlists::set_visibility_handler,
        crate::reads::collections::playlists::add_tracks_handler,
        crate::reads::collections::playlists::remove_tracks_handler,
        crate::reads::collections::playlists::remove_track_handler,
        crate::reads::collections::playlists::reorder_track_handler,
        crate::reads::collections::playlists::update_track_handler,
        crate::reads::collections::playlists::check_tracks_handler,
        crate::reads::collections::playlists::resolve_sources_handler,
        crate::reads::collections::playlists::upload_cover_handler,
        crate::reads::collections::playlists::get_cover_handler,
        crate::reads::collections::playlists::remove_cover_handler,
        crate::reads::collections::favorites::list_favorites_handler,
        crate::reads::collections::favorites::set_favorite_handler,
        crate::reads::collections::follows::get_follow_status_handler,
        crate::reads::collections::follows::set_follow_handler,
        crate::reads::collections::follows::set_auto_download_handler,
        crate::reads::collections::follows::list_followed_artists_handler,
        crate::reads::collections::follows::list_new_releases_handler,
        crate::reads::collections::follows::list_recent_releases_handler,
        crate::reads::collections::follows::unseen_count_handler,
        crate::reads::collections::follows::mark_seen_handler,
        crate::reads::collections::approvals::list_approvals_handler,
        crate::reads::collections::approvals::list_approval_batches_handler,
        crate::reads::collections::pins::get_pin_handler,
        crate::reads::collections::pins::set_pin_handler,
        crate::reads::collections::pins::clear_pin_handler,
        crate::reads::platform::covers::cover_from_release_group,
        crate::reads::platform::covers::cover_from_release,
        crate::reads::platform::covers::artist_cover,
        crate::reads::platform::version::get_version,
        crate::reads::platform::version::check_update,
        crate::reads::platform::version::get_releases,
        crate::reads::platform::wrapped::get_wrapped_users,
        crate::reads::platform::wrapped::get_wrapped_user,
        crate::reads::platform::wrapped::get_wrapped_server,
        crate::remotes::handlers::get_hub,
        crate::remotes::handlers::get_stats,
        crate::remotes::handlers::list_albums,
        crate::remotes::handlers::get_album,
        crate::remotes::handlers::list_album_tracks,
        crate::remotes::handlers::list_artists,
        crate::remotes::handlers::get_artist_index,
        crate::remotes::handlers::get_artist,
        crate::remotes::handlers::list_tracks,
        crate::remotes::handlers::search,
        crate::remotes::handlers::get_recent,
        crate::remotes::handlers::get_recently_added,
        crate::remotes::handlers::get_favorites,
        crate::remotes::handlers::list_genres,
        crate::remotes::handlers::list_genre_songs,
        crate::remotes::handlers::list_playlists,
        crate::remotes::handlers::get_playlist,
        crate::remotes::handlers::import_playlist,
        crate::remotes::handlers::get_artist_info,
        crate::remotes::handlers::get_album_info,
        crate::remotes::handlers::get_lyrics,
        crate::remotes::handlers::get_top_songs,
        crate::remotes::handlers::get_similar,
        crate::remotes::handlers::get_random,
        crate::remotes::handlers::get_discovery,
        crate::remotes::handlers::get_mix,
        crate::remotes::handlers::list_sessions,
        crate::remotes::handlers::list_history,
        crate::remotes::handlers::get_image,
        crate::remotes::handlers::get_playlist_cover,
        crate::remotes::handlers::match_album,
        crate::remotes::handlers::get_connection,
        crate::remotes::handlers::put_connection,
        crate::remotes::handlers::delete_connection,
        crate::remotes::handlers::get_folders,
        crate::remotes::handlers::put_folders,
        crate::stream::routes::doc_stream_get,
        crate::stream::routes::doc_stream_head,
        crate::playback::handlers::start_playback,
        crate::playback::handlers::report_progress,
        crate::playback::handlers::stop_playback,
        crate::playback::handlers::submit_scrobble,
        crate::playback::handlers::forward_now_playing,
        crate::playback::handlers::now_playing,
        crate::playback::handlers::heartbeat,
        crate::playback::handlers::clear_now_playing,
        crate::acquire::requests::intake::request_album_handler,
        crate::acquire::requests::intake::request_track_handler,
        crate::acquire::requests::intake::request_batch_handler,
        crate::acquire::requests::intake::cancel_batch_handler,
        crate::acquire::requests::intake::cancel_one_handler,
        crate::acquire::requests::intake::retry_one_handler,
        crate::acquire::requests::intake::clear_history_handler,
        crate::acquire::requests::intake::acquire_edition_handler,
        crate::acquire::requests::views::approvals_handler,
        crate::acquire::requests::views::approvals_count_handler,
        crate::acquire::requests::views::approve_handler,
        crate::acquire::requests::views::reject_handler,
        crate::acquire::requests::views::approve_auto_download_handler,
        crate::acquire::requests::views::reject_auto_download_handler,
        crate::acquire::requests::views::revoke_auto_download_handler,
        crate::acquire::requests::views::approve_auto_download_batch_handler,
        crate::acquire::requests::views::reject_auto_download_batch_handler,
        crate::acquire::requests::views::mix_approvals_handler,
        crate::acquire::requests::views::approve_mix_handler,
        crate::acquire::requests::views::reject_mix_handler,
        crate::acquire::requests::views::revoke_mix_handler,
        crate::acquire::requests::views::active_handler,
        crate::acquire::requests::views::active_count_handler,
        crate::acquire::requests::views::history_handler,
        crate::acquire::requests::views::wanted_handler,
        crate::acquire::requests::views::wanted_stop_handler,
        crate::acquire::requests::views::wanted_resume_handler,
        crate::acquire::requests::views::wanted_seen_handler,
        crate::acquire::requests::views::refresh_mix_handler,
        crate::acquire::requests::views::sync_handler,
        crate::acquire::downloads::http::reimport_task_handler,
        crate::acquire::imports::handlers::get_lidarr_config,
        crate::acquire::imports::handlers::put_lidarr_config,
        crate::acquire::imports::handlers::test_lidarr,
        crate::acquire::imports::handlers::list_lidarr_artists,
        crate::acquire::imports::handlers::import_lidarr,
        crate::acquire::imports::handlers::get_spotify_settings,
        crate::acquire::imports::handlers::put_spotify_settings,
        crate::acquire::imports::handlers::get_spotify_redirect_uri,
        crate::acquire::imports::handlers::get_spotify_auth_url,
        crate::acquire::imports::handlers::spotify_callback,
        crate::acquire::imports::handlers::list_spotify_playlists,
        crate::acquire::imports::handlers::import_spotify_playlist,
        crate::acquire::imports::handlers::get_spotify_job,
        crate::acquire::imports::handlers::get_health,
        crate::acquire::imports::handlers::get_slskd_status,
        crate::acquire::imports::handlers::get_sabnzbd_status,
        crate::library::http::handlers::list_roots,
        crate::library::http::handlers::add_root,
        crate::library::http::handlers::trigger_scan,
        crate::library::http::handlers::list_runs,
        crate::library::http::handlers::get_run,
        crate::library::http::handlers::enqueue_identify,
        crate::library::http::handlers::list_reviews,
        crate::library::http::handlers::approve_review,
        crate::library::http::handlers::reject_review,
        crate::library::http::handlers::manage_preview,
        crate::library::http::handlers::manage_apply,
        crate::library::http::handlers::manage_undo,
        crate::library::http::handlers::baseline_restore,
        crate::admin::handlers::list_backups,
        crate::admin::handlers::run_backup,
        crate::admin::handlers::restore_report,
        crate::admin::handlers::cache_stats,
        crate::admin::handlers::clear_cache,
        crate::admin::handlers::queue_stats,
        crate::admin::handlers::provider_stats,
        crate::admin::handlers::get_quota,
        crate::admin::handlers::set_quota,
        crate::admin::handlers::run_precache,
        crate::plugins::handlers::list_plugins,
        crate::plugins::handlers::install_plugin,
        crate::plugins::handlers::update_plugin,
        crate::plugins::handlers::uninstall_plugin,
        crate::plugins::handlers::list_plugin_sources,
        crate::plugins::handlers::plugin_ext_get,
        crate::plugins::handlers::plugin_ext_post,
        crate::plugins::handlers::plugin_ext_delete,
        crate::plugins::handlers::plugin_panel_js,
        crate::plugins::handlers::get_scrobble_preferences,
        crate::plugins::handlers::update_scrobble_preferences,
        crate::plugins::handlers::connect_listenbrainz_route,
        crate::plugins::handlers::listenbrainz_status,
        crate::plugins::handlers::disconnect_listenbrainz_route,
        crate::jobs::playlist_sync::doc_sync_now,
        crate::settings::handlers::get_preferences,
        crate::settings::handlers::put_preferences,
        crate::settings::handlers::get_schedule,
        crate::settings::handlers::put_schedule,
        crate::settings::handlers::get_watcher,
        crate::settings::handlers::put_watcher,
        crate::settings::handlers::get_library,
        crate::settings::handlers::put_library,
        crate::settings::handlers::add_library_path,
        crate::settings::handlers::remove_library_path,
        crate::settings::handlers::get_advanced,
        crate::settings::handlers::put_advanced,
        crate::settings::handlers::get_cache_ttls,
        crate::settings::handlers::get_jellyfin,
        crate::settings::handlers::put_jellyfin,
        crate::settings::handlers::verify_jellyfin,
        crate::settings::handlers::get_navidrome,
        crate::settings::handlers::put_navidrome,
        crate::settings::handlers::verify_navidrome,
        crate::settings::handlers::get_plex,
        crate::settings::handlers::put_plex,
        crate::settings::handlers::verify_plex,
        crate::settings::handlers::get_plex_libraries,
        crate::settings::handlers::get_listenbrainz,
        crate::settings::handlers::put_listenbrainz,
        crate::settings::handlers::verify_listenbrainz,
        crate::settings::handlers::get_youtube,
        crate::settings::handlers::put_youtube,
        crate::settings::handlers::verify_youtube,
        crate::settings::handlers::get_events,
        crate::settings::handlers::put_events,
        crate::settings::handlers::test_ticketmaster,
        crate::settings::handlers::test_skiddle,
        crate::settings::handlers::get_wrapped,
        crate::settings::handlers::put_wrapped,
        crate::settings::handlers::get_scrobble,
        crate::settings::handlers::put_scrobble,
        crate::settings::handlers::get_primary_source,
        crate::settings::handlers::put_primary_source,
        crate::settings::handlers::get_lastfm,
        crate::settings::handlers::put_lastfm,
        crate::settings::handlers::get_free_music,
        crate::settings::handlers::put_free_music,
        crate::settings::handlers::get_get_it,
        crate::settings::handlers::put_get_it,
        crate::settings::handlers::get_security,
        crate::settings::handlers::put_security,
        crate::settings::handlers::verify_hibp,
        crate::settings::handlers::get_oidc,
        crate::settings::handlers::put_oidc,
        crate::settings::handlers::verify_oidc,
        crate::settings::handlers::get_connect_apps,
        crate::settings::handlers::put_connect_apps,
        crate::settings::handlers::get_musicbrainz,
        crate::settings::handlers::put_musicbrainz,
        crate::settings::handlers::stage_brainzmash,
        crate::settings::handlers::consent_brainzmash,
        crate::settings::handlers::verify_musicbrainz,
        crate::settings::handlers::activate_brainzmash,
        crate::settings::handlers::get_slskd,
        crate::settings::handlers::put_slskd,
        crate::settings::handlers::test_slskd,
        crate::settings::handlers::get_sabnzbd,
        crate::settings::handlers::put_sabnzbd,
        crate::settings::handlers::test_sabnzbd,
        crate::settings::handlers::get_source_priority,
        crate::settings::handlers::put_source_priority,
        crate::settings::handlers::get_wanted,
        crate::settings::handlers::put_wanted,
        crate::settings::handlers::get_policy,
        crate::settings::handlers::put_policy,
        crate::settings::handlers::get_policy_summary,
        crate::settings::handlers::post_policy_impact,
        crate::settings::handlers::list_indexers,
        crate::settings::handlers::create_indexer,
        crate::settings::handlers::update_indexer,
        crate::settings::handlers::delete_indexer,
        crate::settings::handlers::reorder_indexers,
        crate::settings::handlers::test_indexer,
        crate::settings::handlers::get_search_backend,
        crate::settings::handlers::put_search_backend,
        crate::settings::handlers::get_prowlarr,
        crate::settings::handlers::put_prowlarr,
        crate::settings::handlers::test_prowlarr,
        crate::settings::handlers::dropped_library_sync,
        crate::settings::handlers::dropped_library_sync_put,
        crate::settings::handlers::dropped_home,
        crate::settings::handlers::dropped_home_put,
        crate::settings::handlers::get_section_prefs,
        crate::settings::handlers::put_section_prefs,
    ),
    components(schemas(
        HealthResponse,
        ErrorEnvelope,
        ErrorBody,
        UserResponse,
        ProfileResponse,
        DisplayNameUpdate,
        UsernameUpdate,
        EmailUpdate,
        PasswordChange,
        LocalPasswordSet,
        AvatarUpload,
        SessionView,
        SessionListResponse,
        DeviceSessionMint,
        DeviceSessionResponse,
        AdminUserCreate,
        AdminUserListResponse,
        RoleUpdate,
        RecoveryCodeResponse,
        PasswordReset,
        LastFmStatusResponse,
        LastFmCredentialsSet,
        LastFmConfiguredResponse,
        LastFmTokenResponse,
        LastFmSessionExchange,
        LastFmSessionResponse,
        AppPasswordView,
        AppPasswordListResponse,
        AppPasswordCreate,
        AppPasswordCreatedResponse,
        AdminAppPasswordView,
        AdminAppPasswordListResponse,
        ImportCandidateView,
        ImportCandidateListResponse,
        ImportUsersRequest,
        ImportUsersResponse,
        TransportDto,
        LoginBody,
        SetupBody,
        SetupStatusBody,
        FederatedUserView,
        JellyfinLoginBody,
        OidcCallbackQuery,
        OidcAuthorizeBody,
        OidcExchangeBody,
        PlexStartBody,
        PlexPinBody,
        PlexLoginPollBody,
        PlexLoginPollResult,
        PlexProfileView,
        PlexLinkPollResult,
        PlexConnectPollResult,
        AlbumCard,
        AlbumCardPage,
        AlbumPage,
        AlbumView,
        ArtistPage,
        ArtistView,
        DecadeShelf,
        DecadesResponse,
        GenreList,
        GenreView,
        LyricLine,
        LyricsView,
        SearchResults,
        StatsView,
        SuggestionTrack,
        SuggestionsResponse,
        TrackPage,
        TrackView,
        AlbumEnrichment,
        AlbumEnrichmentRequest,
        ArtistEnrichment,
        ArtistEnrichmentRequest,
        Degradation,
        EnrichmentBatchRequest,
        EnrichmentResponse,
        EnrichmentSource,
        SearchBucketResponse,
        SearchKind,
        SearchResponse,
        SearchResultItem,
        SuggestResponse,
        SuggestResult,
        AlbumPreviewResponse,
        BecauseYouListenTo,
        ChartAlbum,
        ChartArtist,
        ChartGenre,
        ChartRange,
        ChartSection,
        ChartSource,
        ChartTrack,
        DiscoverActivityRequest,
        DiscoverActivityResponse,
        DiscoverPreview,
        DiscoverQueuePreview,
        DiscoverQueueResponse,
        DiscoverQueueStatusResponse,
        DiscoverResponse,
        DiscoveryBatchCreate,
        DiscoveryBatchDetail,
        DiscoveryBatchItemIn,
        DiscoveryBatchItemStatus,
        DiscoveryBatchListResponse,
        DiscoveryBatchRemoveResult,
        DiscoveryBatchSummary,
        GenreArtwork,
        GenreArtworkAlbum,
        GenreDetailResponse,
        GenreLibrarySection,
        GenrePopularSection,
        HomeResponse,
        IgnoredRelease,
        IgnoredReleasesResponse,
        IntegrationStatus,
        PlaylistProfile,
        PlaylistSuggestionsRequest,
        PlaylistSuggestionsResponse,
        PopularAlbumsPage,
        PreviewTrackItem,
        QueueEnrichment,
        QueueGenerateRequest,
        QueueGenerateResponse,
        QueueIgnoreRequest,
        QueueItem,
        QueueItemFull,
        QueueItemLight,
        QueueValidateRequest,
        QueueValidateResponse,
        RadioPlanRequest,
        RadioPlanResponse,
        RadioPlanTrack,
        RadioRequest,
        RadioSeedItem,
        RefreshResponse,
        SectionItem,
        ServicePrompt,
        TopPickItem,
        TopPicksSection,
        TrackCacheCheckItem,
        TrackCacheCheckRequest,
        TrackCacheCheckResponse,
        TrackCacheCheckResponseItem,
        TrackPreviewResponse,
        TrendingArtistsPage,
        WeeklyExploration,
        WeeklyTrack,
        YouTubeQuotaResponse,
        YouTubeSearchResponse,
        AddTracksBody,
        AddTracksResponse,
        ApprovalBatchItem,
        ApprovalBatchListResponse,
        AutoDownloadApprovalItem,
        AutoDownloadApprovalListResponse,
        AutoDownloadBody,
        CheckTracksBody,
        CheckTracksResponse,
        CoverUploadBody,
        CoverUploadResponse,
        CreatePlaylistBody,
        EditionPinBody,
        EditionPinResponse,
        FavoriteCounts,
        FavoriteItem,
        FavoriteListResponse,
        FavoriteQuery,
        FavoriteStatusResponse,
        FollowBody,
        FollowStatusResponse,
        FollowedArtist,
        FollowedArtistListResponse,
        NewReleaseItem,
        NewReleaseListResponse,
        PlaylistDetail,
        PlaylistListItem,
        PlaylistListResponse,
        PlaylistSummary,
        PlaylistTrack,
        RedactedPlaylist,
        RemoveTracksBody,
        RemoveTracksResponse,
        ReorderBody,
        ReorderResponse,
        ResolveSourcesResponse,
        SetFavoriteBody,
        StatusResponse,
        TrackIdentifier,
        TrackInput,
        UnseenCountResponse,
        UpdatePlaylistBody,
        UpdateTrackBody,
        VisibilityBody,
        GitHubRelease,
        UpdateCheckResponse,
        VersionInfo,
        ServerWrappedResponse,
        UserWrappedResponse,
        WrappedAlbum,
        WrappedArtist,
        WrappedGenre,
        WrappedLeaderboardEntry,
        WrappedTrack,
        WrappedUserSummary,
        WrappedUsersResponse,
        SourceName,
        RemotesAlbumView,
        RemotesArtistView,
        RemotesTrackView,
        RemotesAlbumPage,
        RemotesArtistPage,
        RemotesTrackPage,
        ArtistIndexEntry,
        ArtistIndex,
        RemotesSearchResults,
        RemotesStatsView,
        HubView,
        DiscoveryHubView,
        DiscoveryView,
        FavoritesView,
        RemotesPlaylistSummary,
        PlaylistCollection,
        RemotesPlaylistDetail,
        ImportResult,
        InfoView,
        RemotesLyricLine,
        RemotesLyricsView,
        RemotesSessionView,
        SessionsView,
        HistoryEntry,
        HistoryPage,
        MatchView,
        ConnectionStatus,
        ConnectionSave,
        MusicFolderView,
        FolderResolutionView,
        FolderSave,
        PlaybackStartRequest,
        PlaybackStartResponse,
        PlaybackProgressRequest,
        PlaybackProgressResponse,
        PlaybackStopRequest,
        PlaybackStopResponse,
        ScrobbleSubmitRequest,
        ScrobbleNowPlayingRequest,
        ServiceResult,
        ScrobbleResponse,
        NowPlayingHeartbeat,
        NowPlayingDeleteQuery,
        NowPlayingEntry,
        NowPlayingSnapshot,
        AlbumIntake,
        TrackIntake,
        BatchItem,
        BatchIntake,
        BatchCancelBody,
        KindQuery,
        HistoryQuery,
        IntakeResponse,
        TrackIntakeResponse,
        BatchIntakeResponse,
        BatchCancelResponse,
        RequestItem,
        RequestStatusMessage,
        ReimportResponse,
        ActiveRequestsResponse,
        ActiveCountResponse,
        HistoryResponse,
        ActionResponse,
        ClearHistoryResponse,
        WantedItem,
        WantedRetryingItem,
        WantedResponse,
        WantedActionResponse,
        PersonalMixApprovalItem,
        PersonalMixApprovalsResponse,
        RequestsRefreshResponse,
        EditionAcquireResponse,
        SyncResponse,
        LidarrConnectionSettings,
        LidarrTestResponse,
        LidarrArtistCandidate,
        LidarrArtistListResponse,
        LidarrImportRequest,
        LidarrImportResponse,
        SpotifySettings,
        SpotifyRedirectUri,
        SpotifyAuthUrlResponse,
        SpotifyPlaylistItem,
        SpotifyPlaylistListResponse,
        SpotifyImportRequest,
        SpotifyImportResponse,
        SpotifyJobStatus,
        SourceGate,
        AcquireHealth,
        SlskdStatusResponse,
        SabnzbdStatusResponse,
        RootView,
        RootsResponse,
        AddRootBody,
        ScanBody,
        ScanResponse,
        ScanRunView,
        ScanRunsResponse,
        ScanScopeView,
        ScanFileView,
        RunDetailResponse,
        IdentifyBody,
        IdentifyResponse,
        CandidateView,
        ReviewView,
        ReviewsResponse,
        ApproveBody,
        IdentityView,
        ReviewResolveResponse,
        ManageItemBody,
        ManagePreviewBody,
        ManageFileView,
        ManagePreviewResponse,
        ManageApplyBody,
        ManageAppliedFile,
        ManageApplyResponse,
        ManageUndoBody,
        ManageUndoResponse,
        BaselineRestoreBody,
        BaselineRestoreResponse,
        BackupListResponse,
        BackupView,
        BackupRunResponse,
        RestoreReport,
        RestoreCheck,
        CacheStatsResponse,
        CacheClearBody,
        CacheClearResponse,
        QueueStatsResponse,
        WakeupChannelView,
        JobView,
        ProviderStatsResponse,
        ProviderLimiterView,
        SlotView,
        QuotaResponse,
        QuotaOverrideBody,
        QuotaOverrideView,
        CheckpointView,
        PrecacheRunResponse,
        PluginSettingFieldInfo,
        PluginInfo,
        PluginListResponse,
        PluginUpdateRequest,
        PluginInstallRequest,
        PluginSource,
        PluginSourcesResponse,
        PluginConnectionStatus,
        ScrobblePreferences,
        ScrobblePreferencesUpdate,
        ListenBrainzConnectRequest,
        StatusMessage,
        crate::jobs::playlist_sync::PlaylistSyncResult,
        AdvancedSettingsDto,
        AudioFormatDto,
        BrainzmashActiveBindingDto,
        BrainzmashPendingProposalDto,
        ConnectAppsDto,
        DiscoverModeDto,
        DownloadAccessDto,
        DownloadPolicyDto,
        EventsSettingsDto,
        EventsSweepScopeDto,
        FilesystemWatcherDto,
        FreeMusicDto,
        FrontendCacheTTLs,
        GetItDto,
        IdentificationPolicyDto,
        IndexerReorderRequest,
        IndexerSavedResponse,
        IndexerTestResponse,
        JellyfinConnectionDto,
        JellyfinUserInfo,
        JellyfinVerifyResponse,
        LastFmSettingsDto,
        LibraryPathRequest,
        LibraryPathRuleDto,
        LibraryRootDto,
        LibraryScanScheduleDto,
        LibraryScanScheduleResponse,
        LibrarySettingsDto,
        LibrarySettingsResponse,
        LibrarySettingsSaveRequest,
        ListenBrainzConnectionDto,
        MbSourceModeDto,
        MusicBrainzBindingRequest,
        MusicBrainzSettingsDto,
        MusicBrainzSettingsUpdate,
        MusicBrainzVerifyRequest,
        MusicSourceDto,
        NavidromeConnectionDto,
        NewznabIndexerDto,
        OidcConnectionDto,
        OperationResult,
        PlexConnectionDto,
        PlexLibrarySectionInfo,
        PlexVerifyResponse,
        PolicyImpactResponse,
        PolicySummaryResponse,
        PrimaryMusicSourceDto,
        ProwlarrConnectionDto,
        ProwlarrTestResponse,
        QualityRecipeEntryDto,
        SabnzbdConnectionDto,
        SabnzbdTestResponse,
        ScanFrequencyDto,
        ScrobbleSettingsDto,
        SectionPrefItem,
        SectionPrefUpdateItem,
        SectionPrefsResponse,
        SectionPrefsUpdate,
        SecuritySettingsDto,
        SlskdConnectionDto,
        SourcePriorityDto,
        TestConnectionResponse,
        UsenetBackendDto,
        UsenetSearchBackendDto,
        UserPreferencesDto,
        VerifyConnectionResponse,
        WantedWatcherDto,
        WrappedSettingsDto,
        YouTubeConnectionDto,
    )),
    info(
        title = "DroppedNeedle v3",
        version = "3.0.0",
        description = "Native API contract. Generated clients must never be hand-edited."
    )
)]
pub struct ApiDoc;
